"""Card-tab "Generate code" snippets — Slide / Color / Scale / Shake
/ Card Enter / Stagger.
"""

from __future__ import annotations

from app.ui.transitions_demo.code_generators.base import (
    HSL_HELPER, assemble_module,
)


def generate_card_code(name: str, easing_name: str, duration: float) -> str:
    if name == "Reset":
        return (
            "# Reset is not an animation — it just snaps the card back\n"
            "# to its starting position. Pick Slide / Color / Scale /\n"
            "# Shake / Card Enter / Stagger and click Generate code.\n"
        )

    easings_needed = {easing_name}
    needs_math = name == "Shake"
    needs_colorsys = name in ("Color", "Card Enter", "Stagger")
    extra_helpers = [HSL_HELPER] if needs_colorsys else None

    # Shake uses linear ease (the sine wave already shapes the motion).
    if name == "Shake":
        easings_needed.add("linear")

    title = f"Card animation — {name} (generated by Transitions Demo)."
    settings = {
        "Animation": name,
        "Easing": easing_name,
        "Duration": f"{duration}s",
    }

    if name == "Slide":
        body = (
            f"def animate_card(card):\n"
            f"    start_x, end_x = 0.2, 0.8\n"
            f"    card.place_configure(relx=start_x, rely=0.5,"
            f' anchor="center")\n'
            f"    Tween(\n"
            f"        card, {duration}, {easing_name},\n"
            f"        lambda t: card.place_configure("
            f"relx=lerp(start_x, end_x, t)),\n"
            f"    ).start()"
        )
    elif name == "Color":
        body = (
            f"BASE_COLOR = '#1f6aa5'\n"
            f"PEAK_COLOR = '#d9534f'\n"
            f"\n"
            f"\n"
            f"def animate_card(card):\n"
            f"    Tween(\n"
            f"        card, {duration}, {easing_name},\n"
            f"        lambda t: card.configure(\n"
            f"            fg_color=lerp_color_hsl(BASE_COLOR, PEAK_COLOR, t)\n"
            f"        ),\n"
            f"    ).start()"
        )
    elif name == "Scale":
        body = (
            f"def animate_card(card, base_w=140, base_h=110):\n"
            f"    PEAK_W, PEAK_H = 220, 70\n"
            f"\n"
            f"    def to_big(t):\n"
            f"        card.configure(\n"
            f"            width=int(lerp(base_w, PEAK_W, t)),\n"
            f"            height=int(lerp(base_h, PEAK_H, t)),\n"
            f"        )\n"
            f"\n"
            f"    def to_small(t):\n"
            f"        card.configure(\n"
            f"            width=int(lerp(PEAK_W, base_w, t)),\n"
            f"            height=int(lerp(PEAK_H, base_h, t)),\n"
            f"        )\n"
            f"\n"
            f"    Tween(\n"
            f"        card, {duration}, {easing_name}, to_big,\n"
            f"        on_done=lambda: card.after(\n"
            f"            250,\n"
            f"            lambda: Tween(\n"
            f"                card, {duration}, {easing_name}, to_small\n"
            f"            ).start(),\n"
            f"        ),\n"
            f"    ).start()"
        )
    elif name == "Shake":
        body = (
            f"def animate_card(card):\n"
            f"    center = 0.5\n"
            f"    AMP = 0.05\n"
            f"\n"
            f"    def step(t):\n"
            f"        offset = math.sin(t * math.pi * 8) * AMP * (1 - t)\n"
            f'        card.place_configure(relx=center + offset,'
            f' rely=0.5, anchor="center")\n'
            f"\n"
            f"    Tween(\n"
            f"        card, {duration}, linear, step,\n"
            f"        on_done=lambda: card.place_configure("
            f'relx=center, rely=0.5, anchor="center"),\n'
            f"    ).start()"
        )
    elif name == "Card Enter":
        body = (
            f"BASE_COLOR = '#1f6aa5'\n"
            f"START_COLOR = '#2d2d30'\n"
            f"\n"
            f"\n"
            f"def animate_card(card, base_w=140, base_h=110):\n"
            f"    START_RELY, END_RELY = 1.35, 0.5\n"
            f"    START_W, START_H = 90, 80\n"
            f"\n"
            f'    card.place_configure(relx=0.5, rely=START_RELY,'
            f' anchor="center")\n'
            f"    card.configure(\n"
            f"        width=START_W, height=START_H, fg_color=START_COLOR\n"
            f"    )\n"
            f"\n"
            f"    def step(t):\n"
            f"        card.place_configure(rely=lerp(START_RELY, END_RELY, t))\n"
            f"        card.configure(\n"
            f"            fg_color=lerp_color_hsl(\n"
            f"                START_COLOR, BASE_COLOR, max(0.0, min(1.0, t))\n"
            f"            ),\n"
            f"            width=int(lerp(START_W, base_w, t)),\n"
            f"            height=int(lerp(START_H, base_h, t)),\n"
            f"        )\n"
            f"\n"
            f"    Tween(card, {duration}, {easing_name}, step).start()"
        )
    else:  # Stagger
        body = (
            f"BASE_COLOR = '#1f6aa5'\n"
            f"START_COLOR = '#2d2d30'\n"
            f"\n"
            f"\n"
            f"def animate_stagger(parent, n=5, item_size=60, gap_ms=80):\n"
            f"    spacing = 0.14\n"
            f"    start_relx = 0.5 - spacing * (n - 1) / 2\n"
            f"    items = []\n"
            f"    for i in range(n):\n"
            f"        f = ctk.CTkFrame(\n"
            f"            parent, width=item_size, height=item_size,\n"
            f"            fg_color=START_COLOR, corner_radius=8,\n"
            f"        )\n"
            f"        f.place(\n"
            f'            relx=start_relx + i * spacing, rely=1.3,'
            f' anchor="center",\n'
            f"        )\n"
            f"        items.append(f)\n"
            f"\n"
            f"    def make_step(f):\n"
            f"        def step(t):\n"
            f"            f.place_configure(rely=lerp(1.3, 0.5, t))\n"
            f"            f.configure(\n"
            f"                fg_color=lerp_color_hsl(\n"
            f"                    START_COLOR, BASE_COLOR,\n"
            f"                    max(0.0, min(1.0, t)),\n"
            f"                )\n"
            f"            )\n"
            f"        return step\n"
            f"\n"
            f"    for i, frame in enumerate(items):\n"
            f"        parent.after(\n"
            f"            i * gap_ms,\n"
            f"            lambda step=make_step(frame): Tween(\n"
            f"                parent, {duration}, {easing_name}, step\n"
            f"            ).start(),\n"
            f"        )"
        )

    if name == "Stagger":
        main_block = (
            "    ctk.set_appearance_mode('dark')\n"
            "    app = ctk.CTk()\n"
            "    app.geometry('600x300')\n"
            "    stage = ctk.CTkFrame(app, fg_color='#252526')\n"
            "    stage.pack(fill='both', expand=True, padx=12, pady=12)\n"
            "    app.after(100, lambda: animate_stagger(stage))\n"
            "    app.mainloop()"
        )
    else:
        main_block = (
            "    ctk.set_appearance_mode('dark')\n"
            "    app = ctk.CTk()\n"
            "    app.geometry('500x260')\n"
            "    card = ctk.CTkFrame(\n"
            "        app, width=140, height=110,\n"
            "        fg_color='#1f6aa5', corner_radius=12,\n"
            "    )\n"
            "    card.place(relx=0.5, rely=0.5, anchor='center')\n"
            "    app.after(200, lambda: animate_card(card))\n"
            "    app.mainloop()"
        )

    return assemble_module(
        title=title,
        settings=settings,
        body=body,
        main_block=main_block,
        easings_needed=easings_needed,
        needs_math=needs_math,
        needs_colorsys=needs_colorsys,
        extra_helpers=extra_helpers,
    )
