"""Loaders-tab "Generate code" snippets — Pulse / Arc / Three Dots /
Shimmer / Progress.

The canvas-based loaders run on a fixed ``LOADER_DURATION`` (3s) with
linear easing because the shapes loop internally; only ``Progress``
honours the user's chosen easing + duration since it's a single
linear fill from 0 → 1.
"""

from __future__ import annotations

from app.ui.transitions_demo.code_generators.base import assemble_module


LOADER_DURATION = 3.0


def generate_loader_code(name: str, easing_name: str, duration: float) -> str:
    title = (
        f"Loading indicator — {name} (generated by Transitions Demo)."
    )

    if name == "Progress":
        settings = {
            "Indicator": name,
            "Easing": easing_name,
            "Duration": f"{duration}s",
        }
        body = (
            f"def animate_progress(bar):\n"
            f"    bar.set(0)\n"
            f"\n"
            f"    def step(t):\n"
            f"        bar.set(max(0.0, min(1.0, t)))\n"
            f"\n"
            f"    Tween(bar, {duration}, {easing_name}, step).start()"
        )
        main_block = (
            "    ctk.set_appearance_mode('dark')\n"
            "    app = ctk.CTk()\n"
            "    app.geometry('500x180')\n"
            "    bar = ctk.CTkProgressBar(app, width=320, height=14)\n"
            "    bar.set(0)\n"
            "    bar.place(relx=0.5, rely=0.5, anchor='center')\n"
            "    app.after(300, lambda: animate_progress(bar))\n"
            "    app.mainloop()"
        )
        return assemble_module(
            title=title,
            settings=settings,
            body=body,
            main_block=main_block,
            easings_needed={easing_name},
        )

    # Canvas-based loaders all use linear easing and run for 3 seconds
    # by default (looping shapes inside one tween).
    settings = {
        "Indicator": name,
        "Easing": "linear (sine/loop driven)",
        "Duration": f"{LOADER_DURATION}s",
    }

    if name == "Pulse":
        body = (
            "def animate_pulse(canvas, fg='#1f6aa5', duration=3.0):\n"
            "    canvas.delete('all')\n"
            "    canvas.update_idletasks()\n"
            "    cx = canvas.winfo_width() // 2\n"
            "    cy = canvas.winfo_height() // 2\n"
            "    base_r = 14\n"
            "    cid = canvas.create_oval(\n"
            "        cx - base_r, cy - base_r,"
            " cx + base_r, cy + base_r,\n"
            "        fill=fg, outline='',\n"
            "    )\n"
            "\n"
            "    def step(t):\n"
            "        pulse = (math.sin(t * 3 * 2 * math.pi) + 1) / 2\n"
            "        r = base_r * (0.5 + pulse * 0.5)\n"
            "        canvas.coords(cid, cx - r, cy - r, cx + r, cy + r)\n"
            "\n"
            "    Tween(canvas, duration, linear, step).start()"
        )
        entry = "animate_pulse(canvas)"
    elif name == "Arc":
        body = (
            "def animate_arc(canvas, fg='#1f6aa5', duration=3.0):\n"
            "    canvas.delete('all')\n"
            "    canvas.update_idletasks()\n"
            "    cx = canvas.winfo_width() // 2\n"
            "    cy = canvas.winfo_height() // 2\n"
            "    r = 18\n"
            "    arc_id = canvas.create_arc(\n"
            "        cx - r, cy - r, cx + r, cy + r,\n"
            "        start=0, extent=270,\n"
            "        outline=fg, width=4, style='arc',\n"
            "    )\n"
            "\n"
            "    def step(t):\n"
            "        angle = -(t * 3 * 360) % 360\n"
            "        canvas.itemconfigure(arc_id, start=angle)\n"
            "\n"
            "    Tween(canvas, duration, linear, step).start()"
        )
        entry = "animate_arc(canvas)"
    elif name == "Three Dots":
        body = (
            "def animate_three_dots(canvas, fg='#1f6aa5', duration=3.0):\n"
            "    canvas.delete('all')\n"
            "    canvas.update_idletasks()\n"
            "    w = canvas.winfo_width()\n"
            "    h = canvas.winfo_height()\n"
            "    cy = h // 2\n"
            "    dot_r = 6\n"
            "    spacing = 22\n"
            "    cx_start = w // 2 - spacing\n"
            "    dots = []\n"
            "    for i in range(3):\n"
            "        cx = cx_start + i * spacing\n"
            "        d = canvas.create_oval(\n"
            "            cx - dot_r, cy - dot_r,"
            " cx + dot_r, cy + dot_r,\n"
            "            fill=fg, outline='',\n"
            "        )\n"
            "        dots.append((d, cx, cy))\n"
            "\n"
            "    AMP = 8\n"
            "    CYCLES = 4\n"
            "\n"
            "    def step(t):\n"
            "        for i, (did, base_x, base_y) in enumerate(dots):\n"
            "            phase = (\n"
            "                t * CYCLES * 2 * math.pi\n"
            "                - i * (2 * math.pi / 3)\n"
            "            )\n"
            "            offset = max(0, math.sin(phase)) * AMP\n"
            "            canvas.coords(\n"
            "                did,\n"
            "                base_x - dot_r, base_y - offset - dot_r,\n"
            "                base_x + dot_r, base_y - offset + dot_r,\n"
            "            )\n"
            "\n"
            "    Tween(canvas, duration, linear, step).start()"
        )
        entry = "animate_three_dots(canvas)"
    else:  # Shimmer
        body = (
            "def animate_shimmer(\n"
            "    canvas, base='#3a3a3a', highlight='#5a5a5a', duration=3.0,\n"
            "):\n"
            "    canvas.delete('all')\n"
            "    canvas.update_idletasks()\n"
            "    w = canvas.winfo_width()\n"
            "    h = canvas.winfo_height()\n"
            "    margin = 24\n"
            "    card_x1 = margin\n"
            "    card_x2 = w - margin\n"
            "    card_y1 = h // 2 - 12\n"
            "    card_y2 = h // 2 + 12\n"
            "    canvas.create_rectangle(\n"
            "        card_x1, card_y1, card_x2, card_y2,\n"
            "        fill=base, outline='',\n"
            "    )\n"
            "    BAND_W = 60\n"
            "    band = canvas.create_rectangle(\n"
            "        card_x1, card_y1, card_x1, card_y2,\n"
            "        fill=highlight, outline='',\n"
            "    )\n"
            "    card_w = card_x2 - card_x1\n"
            "\n"
            "    def step(t):\n"
            "        cycle_t = (t * 2) % 1\n"
            "        x = card_x1 + cycle_t * (card_w + BAND_W) - BAND_W\n"
            "        x_end = x + BAND_W\n"
            "        x_clamped = max(card_x1, x)\n"
            "        x_end_clamped = min(card_x2, x_end)\n"
            "        if x_clamped < x_end_clamped:\n"
            "            canvas.coords(\n"
            "                band, x_clamped, card_y1,\n"
            "                x_end_clamped, card_y2,\n"
            "            )\n"
            "        else:\n"
            "            canvas.coords(band, card_x1, card_y1, card_x1, card_y2)\n"
            "\n"
            "    Tween(canvas, duration, linear, step).start()"
        )
        entry = "animate_shimmer(canvas)"

    body = "import tkinter as tk\n\n\n" + body
    main_block = (
        "    ctk.set_appearance_mode('dark')\n"
        "    app = ctk.CTk()\n"
        "    app.geometry('400x180')\n"
        "    canvas = tk.Canvas(\n"
        "        app, bg='#252526', highlightthickness=0, bd=0,\n"
        "    )\n"
        "    canvas.pack(fill='both', expand=True)\n"
        f"    app.after(300, lambda: {entry})\n"
        "    app.mainloop()"
    )

    return assemble_module(
        title=title,
        settings=settings,
        body=body,
        main_block=main_block,
        easings_needed={"linear"},
        needs_math=True,
    )
