"""Popups-tab "Generate code" snippets — Fade / Pop / Slide-Down /
Slide-Up / Slide-Right / Zoom.
"""

from __future__ import annotations

from app.ui.transitions_demo.code_generators.base import assemble_module


POPUP_PREAMBLE = (
    "POPUP_W, POPUP_H = 400, 140\n"
    "\n"
    "\n"
    "def _make_popup(parent, title):\n"
    "    parent.update_idletasks()\n"
    "    px = parent.winfo_rootx()\n"
    "    py = parent.winfo_rooty()\n"
    "    pw = parent.winfo_width()\n"
    "    ph = parent.winfo_height()\n"
    "    tx = px + (pw - POPUP_W) // 2\n"
    "    ty = py + (ph - POPUP_H) // 2\n"
    "\n"
    "    top = ctk.CTkToplevel(parent)\n"
    "    top.title(title)\n"
    "    top.attributes('-alpha', 0.0)\n"
    "    top.transient(parent)\n"
    "    ctk.CTkLabel(\n"
    "        top, text=title, font=('Segoe UI', 16, 'bold'),\n"
    "    ).pack(expand=True, fill='both')\n"
    "\n"
    "    # Force dark titlebar (Windows DWM defers NC paint past the\n"
    "    # first map; only withdraw+deiconify reliably triggers it).\n"
    "    def _kick():\n"
    "        try:\n"
    "            top.update_idletasks()\n"
    "            top.withdraw()\n"
    "            top.update_idletasks()\n"
    "            top.deiconify()\n"
    "        except tk.TclError:\n"
    "            pass\n"
    "    top.after(50, _kick)\n"
    "    return top, tx, ty"
)


def generate_popup_code(name: str, easing_name: str, duration: float) -> str:
    title = f"Popup animation — {name} (generated by Transitions Demo)."
    settings = {
        "Animation": name,
        "Easing": easing_name,
        "Duration": f"{duration}s",
    }

    if name == "Fade":
        anim = (
            f"def show_popup(parent, title='Popup'):\n"
            f"    top, tx, ty = _make_popup(parent, title)\n"
            f"    top.geometry(f'{{POPUP_W}}x{{POPUP_H}}+{{tx}}+{{ty}}')\n"
            f"    Tween(\n"
            f"        top, {duration}, {easing_name},\n"
            f"        lambda t: top.attributes('-alpha', min(t, 1.0)),\n"
            f"    ).start()\n"
            f"    return top"
        )
    elif name == "Pop":
        anim = (
            f"def show_popup(parent, title='Popup'):\n"
            f"    top, tx, ty = _make_popup(parent, title)\n"
            f"    sw = int(POPUP_W * 0.82)\n"
            f"    sh = int(POPUP_H * 0.82)\n"
            f"    top.geometry(\n"
            f"        f'{{sw}}x{{sh}}+'\n"
            f"        f'{{tx + (POPUP_W - sw) // 2}}+'\n"
            f"        f'{{ty + (POPUP_H - sh) // 2}}'\n"
            f"    )\n"
            f"\n"
            f"    def step(t):\n"
            f"        w = int(lerp(sw, POPUP_W, t))\n"
            f"        h = int(lerp(sh, POPUP_H, t))\n"
            f"        top.geometry(\n"
            f"            f'{{w}}x{{h}}+'\n"
            f"            f'{{tx + (POPUP_W - w) // 2}}+'\n"
            f"            f'{{ty + (POPUP_H - h) // 2}}'\n"
            f"        )\n"
            f"        top.attributes('-alpha', min(t, 1.0))\n"
            f"\n"
            f"    Tween(top, {duration}, {easing_name}, step).start()\n"
            f"    return top"
        )
    elif name == "Slide-Down":
        anim = (
            f"def show_popup(parent, title='Popup'):\n"
            f"    top, tx, ty = _make_popup(parent, title)\n"
            f"    start_y = ty - 240\n"
            f"    top.geometry(f'{{POPUP_W}}x{{POPUP_H}}+{{tx}}+{{start_y}}')\n"
            f"\n"
            f"    def step(t):\n"
            f"        y = int(lerp(start_y, ty, t))\n"
            f"        top.geometry(f'{{POPUP_W}}x{{POPUP_H}}+{{tx}}+{{y}}')\n"
            f"        top.attributes('-alpha', min(t * 1.6, 1.0))\n"
            f"\n"
            f"    Tween(top, {duration}, {easing_name}, step).start()\n"
            f"    return top"
        )
    elif name == "Slide-Up":
        anim = (
            f"def show_popup(parent, title='Popup'):\n"
            f"    top, tx, ty = _make_popup(parent, title)\n"
            f"    start_y = ty + 240\n"
            f"    top.geometry(f'{{POPUP_W}}x{{POPUP_H}}+{{tx}}+{{start_y}}')\n"
            f"\n"
            f"    def step(t):\n"
            f"        y = int(lerp(start_y, ty, t))\n"
            f"        top.geometry(f'{{POPUP_W}}x{{POPUP_H}}+{{tx}}+{{y}}')\n"
            f"        top.attributes('-alpha', min(t * 1.6, 1.0))\n"
            f"\n"
            f"    Tween(top, {duration}, {easing_name}, step).start()\n"
            f"    return top"
        )
    elif name == "Slide-Right":
        anim = (
            f"def show_popup(parent, title='Popup'):\n"
            f"    top, tx, ty = _make_popup(parent, title)\n"
            f"    start_x = tx - 300\n"
            f"    top.geometry(f'{{POPUP_W}}x{{POPUP_H}}+{{start_x}}+{{ty}}')\n"
            f"\n"
            f"    def step(t):\n"
            f"        x = int(lerp(start_x, tx, t))\n"
            f"        top.geometry(f'{{POPUP_W}}x{{POPUP_H}}+{{x}}+{{ty}}')\n"
            f"        top.attributes('-alpha', min(t * 1.6, 1.0))\n"
            f"\n"
            f"    Tween(top, {duration}, {easing_name}, step).start()\n"
            f"    return top"
        )
    else:  # Zoom
        anim = (
            f"def show_popup(parent, title='Popup'):\n"
            f"    top, tx, ty = _make_popup(parent, title)\n"
            f"    sw = int(POPUP_W * 0.4)\n"
            f"    sh = int(POPUP_H * 0.4)\n"
            f"    top.geometry(\n"
            f"        f'{{sw}}x{{sh}}+'\n"
            f"        f'{{tx + (POPUP_W - sw) // 2}}+'\n"
            f"        f'{{ty + (POPUP_H - sh) // 2}}'\n"
            f"    )\n"
            f"\n"
            f"    def step(t):\n"
            f"        w = int(lerp(sw, POPUP_W, t))\n"
            f"        h = int(lerp(sh, POPUP_H, t))\n"
            f"        top.geometry(\n"
            f"            f'{{w}}x{{h}}+'\n"
            f"            f'{{tx + (POPUP_W - w) // 2}}+'\n"
            f"            f'{{ty + (POPUP_H - h) // 2}}'\n"
            f"        )\n"
            f"        top.attributes('-alpha', min(t, 1.0))\n"
            f"\n"
            f"    Tween(top, {duration}, {easing_name}, step).start()\n"
            f"    return top"
        )

    body = (
        "import tkinter as tk\n\n\n"
        + POPUP_PREAMBLE
        + "\n\n\n"
        + anim
    )

    main_block = (
        "    ctk.set_appearance_mode('dark')\n"
        "    app = ctk.CTk()\n"
        "    app.geometry('600x300')\n"
        "    ctk.CTkButton(\n"
        "        app, text='Show popup',\n"
        "        command=lambda: show_popup(app, 'Hello!'),\n"
        "    ).place(relx=0.5, rely=0.5, anchor='center')\n"
        "    app.mainloop()"
    )

    return assemble_module(
        title=title,
        settings=settings,
        body=body,
        main_block=main_block,
        easings_needed={easing_name},
    )
