"""Text-tab "Generate code" snippets — Typewriter / Counter / Wave /
Fade Words.
"""

from __future__ import annotations

from app.ui.transitions_demo.code_generators.base import (
    HSL_HELPER, assemble_module,
)


def generate_text_code(name: str, easing_name: str, duration: float) -> str:
    easings_needed = {easing_name}
    needs_math = name == "Wave"
    needs_colorsys = name == "Fade Words"
    extra_helpers = [HSL_HELPER] if needs_colorsys else None

    # Wave uses linear; Fade Words uses ease_out for per-word fade.
    if name == "Wave":
        easings_needed.add("linear")
    if name == "Fade Words":
        easings_needed.add("ease_out")

    title = f"Text animation — {name} (generated by Transitions Demo)."
    settings = {
        "Animation": name,
        "Easing": easing_name,
        "Duration": f"{duration}s",
    }

    if name == "Typewriter":
        body = (
            f"def animate_typewriter(label, text):\n"
            f'    label.configure(text="")\n'
            f"\n"
            f"    def step(t):\n"
            f"        n = max(0, min(int(len(text) * t + 0.5), len(text)))\n"
            f"        label.configure(text=text[:n])\n"
            f"\n"
            f"    Tween(\n"
            f"        label, {duration}, {easing_name}, step,\n"
            f"        on_done=lambda: label.configure(text=text),\n"
            f"    ).start()"
        )
        main_block = (
            "    ctk.set_appearance_mode('dark')\n"
            "    app = ctk.CTk()\n"
            "    app.geometry('500x180')\n"
            "    label = ctk.CTkLabel(\n"
            "        app, text='', font=('Segoe UI', 16, 'bold'),\n"
            "    )\n"
            "    label.place(relx=0.5, rely=0.5, anchor='center')\n"
            "    app.after(\n"
            "        300,\n"
            "        lambda: animate_typewriter(label, 'Hello, world!'),\n"
            "    )\n"
            "    app.mainloop()"
        )
    elif name == "Counter":
        body = (
            f"def animate_counter(label, end_value, start_value=0):\n"
            f"    label.configure(text=str(start_value))\n"
            f"\n"
            f"    def step(t):\n"
            f"        label.configure(\n"
            f"            text=str(int(lerp(start_value, end_value, t)))\n"
            f"        )\n"
            f"\n"
            f"    Tween(\n"
            f"        label, {duration}, {easing_name}, step,\n"
            f"        on_done=lambda: label.configure(text=str(end_value)),\n"
            f"    ).start()"
        )
        main_block = (
            "    ctk.set_appearance_mode('dark')\n"
            "    app = ctk.CTk()\n"
            "    app.geometry('400x180')\n"
            "    label = ctk.CTkLabel(\n"
            "        app, text='0', font=('Segoe UI', 28, 'bold'),\n"
            "    )\n"
            "    label.place(relx=0.5, rely=0.5, anchor='center')\n"
            "    app.after(300, lambda: animate_counter(label, 100))\n"
            "    app.mainloop()"
        )
    elif name == "Wave":
        body = (
            f"import tkinter as tk\n"
            f"import tkinter.font as tkfont\n"
            f"\n"
            f"\n"
            f"def animate_wave(\n"
            f"    canvas, text, fg='#cccccc',\n"
            f"    family='Segoe UI', size=16, weight='bold',\n"
            f"):\n"
            f"    canvas.delete('all')\n"
            f"    canvas.update_idletasks()\n"
            f"    f = tkfont.Font(family=family, size=size, weight=weight)\n"
            f"    char_widths = [f.measure(ch) for ch in text]\n"
            f"    total_w = sum(char_widths)\n"
            f"    stage_w = canvas.winfo_width()\n"
            f"    stage_h = canvas.winfo_height()\n"
            f"    cy = stage_h // 2\n"
            f"    cur_x = (stage_w - total_w) // 2\n"
            f"    char_ids = []\n"
            f"    for i, ch in enumerate(text):\n"
            f"        cid = canvas.create_text(\n"
            f"            cur_x + char_widths[i] // 2, cy,\n"
            f"            text=ch, font=(family, size, weight),\n"
            f"            fill=fg, anchor='center',\n"
            f"        )\n"
            f"        char_ids.append((cid, cur_x + char_widths[i] // 2, cy))\n"
            f"        cur_x += char_widths[i]\n"
            f"\n"
            f"    AMP = 10\n"
            f"\n"
            f"    def step(t):\n"
            f"        for i, (cid, base_x, base_y) in enumerate(char_ids):\n"
            f"            offset = (\n"
            f"                math.sin(t * math.pi * 4 + i * 0.4)\n"
            f"                * AMP * (1 - t)\n"
            f"            )\n"
            f"            canvas.coords(cid, base_x, base_y + offset)\n"
            f"\n"
            f"    Tween(canvas, {duration}, linear, step).start()"
        )
        main_block = (
            "    ctk.set_appearance_mode('dark')\n"
            "    app = ctk.CTk()\n"
            "    app.geometry('500x180')\n"
            "    canvas = tk.Canvas(\n"
            "        app, bg='#252526', highlightthickness=0, bd=0,\n"
            "    )\n"
            "    canvas.pack(fill='both', expand=True)\n"
            "    app.after(300, lambda: animate_wave(canvas, 'Animated text'))\n"
            "    app.mainloop()"
        )
    else:  # Fade Words
        body = (
            f"BG_COLOR = '#252526'\n"
            f"FG_COLOR = '#cccccc'\n"
            f"\n"
            f"\n"
            f"def animate_fade_words(parent, text, gap_ms=120, per_word_dur=0.5):\n"
            f"    for child in parent.winfo_children():\n"
            f"        child.destroy()\n"
            f"    container = ctk.CTkFrame(parent, fg_color='transparent')\n"
            f"    container.place(relx=0.5, rely=0.5, anchor='center')\n"
            f"\n"
            f"    labels = []\n"
            f"    for word in text.split():\n"
            f"        lbl = ctk.CTkLabel(\n"
            f"            container, text=word,\n"
            f"            font=('Segoe UI', 16, 'bold'), text_color=BG_COLOR,\n"
            f"        )\n"
            f"        lbl.pack(side='left', padx=4)\n"
            f"        labels.append(lbl)\n"
            f"\n"
            f"    def make_step(label):\n"
            f"        def step(t):\n"
            f"            label.configure(\n"
            f"                text_color=lerp_color_hsl(\n"
            f"                    BG_COLOR, FG_COLOR, max(0.0, min(1.0, t))\n"
            f"                )\n"
            f"            )\n"
            f"        return step\n"
            f"\n"
            f"    for i, lbl in enumerate(labels):\n"
            f"        parent.after(\n"
            f"            i * gap_ms,\n"
            f"            lambda step=make_step(lbl): Tween(\n"
            f"                parent, per_word_dur, ease_out, step\n"
            f"            ).start(),\n"
            f"        )"
        )
        main_block = (
            "    ctk.set_appearance_mode('dark')\n"
            "    app = ctk.CTk()\n"
            "    app.geometry('600x180')\n"
            "    stage = ctk.CTkFrame(app, fg_color='#252526')\n"
            "    stage.pack(fill='both', expand=True, padx=12, pady=12)\n"
            "    app.after(\n"
            "        200,\n"
            "        lambda: animate_fade_words(stage, 'Words fade in one by one'),\n"
            "    )\n"
            "    app.mainloop()"
        )

    return assemble_module(
        title=title,
        settings=settings,
        body=body,
        main_block=main_block,
        easings_needed=easings_needed,
        needs_math=needs_math,
        needs_colorsys=needs_colorsys,
        extra_helpers=extra_helpers,
    )
