"""Toasts-tab "Generate code" snippets — Info / Success / Warning /
Error with corner-position selector.
"""

from __future__ import annotations

from app.ui.transitions_demo.code_generators.base import assemble_module


TOAST_ACCENTS = {
    "Info": "#4a9eff",
    "Success": "#6fcf6a",
    "Warning": "#e0a44a",
    "Error": "#d9534f",
}

TOAST_MESSAGES = {
    "Info": "Info: this is informational",
    "Success": "Success: action completed",
    "Warning": "Warning: something to check",
    "Error": "Error: something went wrong",
}


def generate_toast_code(
    name: str, easing_name: str, duration: float, position: str,
) -> str:
    accent = TOAST_ACCENTS.get(name, "#4a9eff")
    message = TOAST_MESSAGES.get(name, name)

    title = f"Toast notification — {name} (generated by Transitions Demo)."
    settings = {
        "Type": name,
        "Position": position,
        "Easing": easing_name,
        "Duration": f"{duration}s",
    }

    body = (
        "import tkinter as tk\n"
        "\n"
        "\n"
        "TOAST_W = 280\n"
        "TOAST_H = 60\n"
        "TOAST_MARGIN = 16\n"
        "TOAST_SPACING = 8\n"
        "TOAST_HOLD_MS = 2000\n"
        "TOAST_SLIDE_OFFSET = 140\n"
        "\n"
        "_toast_stacks = {}\n"
        "\n"
        "\n"
        "def _toast_slot(parent, position, index):\n"
        "    parent.update_idletasks()\n"
        "    win_x = parent.winfo_x()\n"
        "    win_y = parent.winfo_y()\n"
        "    win_w = parent.winfo_width()\n"
        "    win_h = parent.winfo_height()\n"
        "\n"
        "    if 'Right' in position:\n"
        "        x = win_x + win_w - TOAST_W - TOAST_MARGIN\n"
        "    elif 'Left' in position:\n"
        "        x = win_x + TOAST_MARGIN\n"
        "    else:\n"
        "        x = win_x + (win_w - TOAST_W) // 2\n"
        "\n"
        "    if 'Bottom' in position:\n"
        "        y = (\n"
        "            win_y + win_h - TOAST_H - TOAST_MARGIN\n"
        "            - index * (TOAST_H + TOAST_SPACING)\n"
        "        )\n"
        "    else:\n"
        "        y = (\n"
        "            win_y + TOAST_MARGIN\n"
        "            + index * (TOAST_H + TOAST_SPACING)\n"
        "        )\n"
        "    return x, y\n"
        "\n"
        "\n"
        "def _toast_start(position, target_x, target_y):\n"
        "    offset = TOAST_SLIDE_OFFSET\n"
        "    if 'Right' in position:\n"
        "        return target_x + offset, target_y\n"
        "    if 'Left' in position:\n"
        "        return target_x - offset, target_y\n"
        "    if position == 'Top-Center':\n"
        "        return target_x, target_y - offset\n"
        "    return target_x, target_y + offset\n"
        "\n"
        "\n"
        "def _dismiss_toast(toast):\n"
        "    position = getattr(toast, '_toast_position', None)\n"
        "    if position is not None:\n"
        "        stack = _toast_stacks.get(position, [])\n"
        "        if toast in stack:\n"
        "            stack.remove(toast)\n"
        "    try:\n"
        "        toast.destroy()\n"
        "    except tk.TclError:\n"
        "        pass\n"
        "\n"
        "\n"
        f"def show_toast(parent, message, accent='{accent}',"
        f" position='{position}'):\n"
        "    stack = _toast_stacks.setdefault(position, [])\n"
        "    used = {\n"
        "        t._toast_index for t in stack if hasattr(t, '_toast_index')\n"
        "    }\n"
        "    index = 0\n"
        "    while index in used:\n"
        "        index += 1\n"
        "\n"
        "    target_x, target_y = _toast_slot(parent, position, index)\n"
        "    start_x, start_y = _toast_start(position, target_x, target_y)\n"
        "\n"
        "    toast = tk.Toplevel(parent)\n"
        "    toast.overrideredirect(True)\n"
        "    toast.attributes('-alpha', 0.0)\n"
        "    toast.attributes('-topmost', True)\n"
        "    toast.configure(bg='#3c3c3c')\n"
        "    toast._toast_index = index\n"
        "    toast._toast_position = position\n"
        "\n"
        "    inner = tk.Frame(toast, bg='#252526')\n"
        "    inner.pack(fill='both', expand=True, padx=1, pady=1)\n"
        "    tk.Frame(inner, bg=accent, width=4).pack(side='left', fill='y')\n"
        "    ctk.CTkLabel(\n"
        "        inner, text=message,\n"
        "        font=('Segoe UI', 13, 'bold'),\n"
        "        text_color=accent, anchor='w', fg_color='#252526',\n"
        "    ).pack(side='left', padx=12, pady=10, fill='both', expand=True)\n"
        "\n"
        "    toast.geometry(f'{TOAST_W}x{TOAST_H}+{start_x}+{start_y}')\n"
        "    stack.append(toast)\n"
        "\n"
        "    def slide_in(t):\n"
        "        cx = int(lerp(start_x, target_x, t))\n"
        "        cy = int(lerp(start_y, target_y, t))\n"
        "        toast.geometry(f'{TOAST_W}x{TOAST_H}+{cx}+{cy}')\n"
        "        toast.attributes('-alpha', min(t * 1.5, 1.0))\n"
        "\n"
        "    def slide_out():\n"
        "        out_x, out_y = _toast_start(position, target_x, target_y)\n"
        "\n"
        "        def step(t):\n"
        "            cx = int(lerp(target_x, out_x, t))\n"
        "            cy = int(lerp(target_y, out_y, t))\n"
        "            toast.geometry(f'{TOAST_W}x{TOAST_H}+{cx}+{cy}')\n"
        "            toast.attributes('-alpha', 1 - t)\n"
        "\n"
        "        Tween(\n"
        "            toast, 0.3, ease_in, step,\n"
        "            on_done=lambda: _dismiss_toast(toast),\n"
        "        ).start()\n"
        "\n"
        f"    Tween(\n"
        f"        toast, {duration}, {easing_name}, slide_in,\n"
        f"        on_done=lambda: toast.after(TOAST_HOLD_MS, slide_out),\n"
        f"    ).start()\n"
        "    return toast"
    )

    main_block = (
        "    ctk.set_appearance_mode('dark')\n"
        "    app = ctk.CTk()\n"
        "    app.geometry('600x320')\n"
        "    ctk.CTkButton(\n"
        f"        app, text='Show {name}',\n"
        f"        command=lambda: show_toast(app, '{message}'),\n"
        "    ).place(relx=0.5, rely=0.5, anchor='center')\n"
        "    app.mainloop()"
    )

    return assemble_module(
        title=title,
        settings=settings,
        body=body,
        main_block=main_block,
        easings_needed={easing_name, "ease_in"},
    )
